// <auto-generated />
namespace TeknikServisYazılım.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class timeformat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timeformat));
        
        string IMigrationMetadata.Id
        {
            get { return "201805111142374_timeformat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
