// <auto-generated />
namespace TeknikServisYazılım.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class whosupplier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(whosupplier));
        
        string IMigrationMetadata.Id
        {
            get { return "201804070649285_whosupplier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
